export const demoFixtures = [
  {
    id: "article-agent-payments",
    type: "article",
    title: "Why Agent Payments Will Rewire Consumer Software",
    source: "Operator Weekly",
    author: "Mira Xu",
    publishedAt: "2026-08-13T08:00:00+08:00",
    summary: "Explains why payment rails become a core primitive for agent-native apps.",
    body: "Agent payments, tool authorization, and post-purchase workflows are moving into one stack.",
    topics: ["agent payments", "ai agent", "consumer software"],
    qualityScore: 0.94,
    noveltyScore: 0.9,
    businessValueScore: 0.95,
    relationshipScore: 0.2,
    accessibleVia: "public_link",
    url: "https://example.com/agent-payments",
    why: "Strong thesis, actionable framing, and directly aligned with AI agent monetization.",
    duplicateGroup: "agents-payments-01"
  },
  {
    id: "article-marketing-funnel",
    type: "article",
    title: "10 AI tricks to 100x your funnel",
    source: "Growth Rocket",
    author: "Promo Team",
    publishedAt: "2026-08-13T09:10:00+08:00",
    summary: "A generic marketing post with little original information.",
    body: "Mostly recycled advice and high-pressure CTA wording.",
    topics: ["marketing", "growth"],
    qualityScore: 0.24,
    noveltyScore: 0.1,
    businessValueScore: 0.2,
    relationshipScore: 0.1,
    accessibleVia: "forwarded_message",
    why: "Likely filtered out as low-signal marketing content.",
    duplicateGroup: "growth-spam-01"
  },
  {
    id: "person-liu-bd",
    type: "message",
    sender: "Liu Yan",
    contactId: "liu-yan",
    title: "Partnership lead from Shenzhen robotics incubator",
    publishedAt: "2026-08-13T10:05:00+08:00",
    body: "We are exploring AI Agent infra partners for a September incubator batch. Can you talk this week?",
    topics: ["partnership", "ai agent", "startup"],
    qualityScore: 0.88,
    noveltyScore: 0.86,
    businessValueScore: 0.93,
    relationshipScore: 0.84,
    waitingHours: 6,
    urgencyScore: 0.8,
    accessibleVia: "bot_event",
    why: "High business value and needs a timely response.",
    replyContext: {
      relationship: "warm",
      lastThreadState: "awaiting_user_reply"
    }
  },
  {
    id: "pdf-agent-state",
    type: "file",
    title: "2026 China Agent Landscape.pdf",
    sender: "Chen Rui",
    contactId: "chen-rui",
    publishedAt: "2026-08-13T11:30:00+08:00",
    body: "Industry map, investment signals, and competitor notes.",
    topics: ["ai agent", "china startup", "fundraising"],
    qualityScore: 0.9,
    noveltyScore: 0.82,
    businessValueScore: 0.89,
    relationshipScore: 0.71,
    urgencyScore: 0.55,
    accessibleVia: "forwarded_file",
    why: "Dense source material with direct market intelligence.",
    fileName: "china-agent-landscape-2026.pdf"
  },
  {
    id: "job-shenzhen-operator",
    type: "opportunity",
    title: "Founding Agent Operator role in Shenzhen",
    sender: "He Jun",
    contactId: "he-jun",
    publishedAt: "2026-08-13T12:20:00+08:00",
    body: "Looking for an operator who can ship AI workflow products. Salary is competitive. Deadline August 20, 2026.",
    topics: ["job", "shenzhen", "agent operator"],
    qualityScore: 0.8,
    noveltyScore: 0.77,
    businessValueScore: 0.74,
    relationshipScore: 0.62,
    urgencyScore: 0.7,
    accessibleVia: "bot_event",
    deadline: "2026-08-20",
    why: "Relevant opportunity with a clear deadline and real operator fit."
  },
  {
    id: "competition-agent-finance",
    type: "opportunity",
    title: "Agent Finance Demo Day",
    sender: "Ning Lab",
    contactId: "ning-lab",
    publishedAt: "2026-08-13T14:10:00+08:00",
    body: "Demo day for AI agents in payments, finance, and social commerce. Apply by August 18, 2026.",
    topics: ["competition", "agent payments", "fundraising"],
    qualityScore: 0.85,
    noveltyScore: 0.79,
    businessValueScore: 0.84,
    relationshipScore: 0.44,
    urgencyScore: 0.75,
    accessibleVia: "public_link",
    deadline: "2026-08-18",
    why: "Strategically aligned and time-sensitive."
  },
  {
    id: "article-social-agents",
    type: "article",
    title: "Social Agents Need Memory More Than Chat",
    source: "Frontier Notes",
    author: "Ada Lin",
    publishedAt: "2026-08-13T15:15:00+08:00",
    summary: "Argues that persistent personal memory beats generic assistant UX.",
    body: "Memory, ranking, and relationship context define the usefulness of personal agents.",
    topics: ["ai social", "memory", "agent design"],
    qualityScore: 0.92,
    noveltyScore: 0.87,
    businessValueScore: 0.9,
    relationshipScore: 0.18,
    accessibleVia: "public_link",
    url: "https://example.com/social-agents-memory",
    why: "Directly maps to product strategy and long-term memory design.",
    duplicateGroup: "social-agents-memory-01"
  },
  {
    id: "message-investor-followup",
    type: "message",
    sender: "Zoe Capital",
    contactId: "zoe-capital",
    title: "Investor follow-up on your agent infrastructure deck",
    publishedAt: "2026-08-13T16:05:00+08:00",
    body: "We liked the direction. Can you clarify your moat, GTM, and whether WeChat is only a distribution layer?",
    topics: ["fundraising", "ai agent", "moat"],
    qualityScore: 0.93,
    noveltyScore: 0.84,
    businessValueScore: 0.98,
    relationshipScore: 0.91,
    waitingHours: 3,
    urgencyScore: 0.82,
    accessibleVia: "bot_event",
    why: "High-stakes investor thread that should not wait.",
    replyContext: {
      relationship: "hot",
      lastThreadState: "awaiting_user_reply"
    }
  },
  {
    id: "message-friend-low-priority",
    type: "message",
    sender: "A Bo",
    contactId: "abo",
    title: "Weekend basketball?",
    publishedAt: "2026-08-13T17:40:00+08:00",
    body: "Want to play ball this weekend?",
    topics: ["social"],
    qualityScore: 0.52,
    noveltyScore: 0.2,
    businessValueScore: 0.18,
    relationshipScore: 0.65,
    waitingHours: 1,
    urgencyScore: 0.2,
    accessibleVia: "bot_event",
    why: "A real relationship ping, but not among the most urgent items."
  }
]

export function getDemoFixtures() {
  return demoFixtures.map(item => ({ ...item }))
}

